---@meta

-- Generated by tools/generate_lua_api_stubs.py from RegisterLua*Bindings.
-- Do not edit by hand. Runtime documentation defines precise values and shapes.
-- Inventory: 29 namespaces, 267 unique functions.

---@class SdRuntimeApi
local sd_runtime = {}

---@param ... any
---@return any
function sd_runtime.get_mod(...) end

---@param ... any
---@return any
function sd_runtime.get_multiplayer_state(...) end

---@param ... any
---@return any
function sd_runtime.get_frame_state(...) end

---@param ... any
---@return any
function sd_runtime.choose_level_up_option(...) end

---@param ... any
---@return any
function sd_runtime.debug_publish_level_up_offer(...) end

---@param ... any
---@return any
function sd_runtime.has_capability(...) end

---@param ... any
---@return any
function sd_runtime.get_capabilities(...) end

---@param ... any
---@return any
function sd_runtime.get_environment_variable(...) end

---@param ... any
---@return any
function sd_runtime.get_mod_text_file(...) end

---@class SdEventsApi
local sd_events = {}

---@param ... any
---@return any
function sd_events.on(...) end

---@class SdStateApi
local sd_state = {}

---@param ... any
---@return any
function sd_state.get(...) end

---@param ... any
---@return any
function sd_state.set(...) end

---@param ... any
---@return any
function sd_state.delete(...) end

---@param ... any
---@return any
function sd_state.clear(...) end

---@param ... any
---@return any
function sd_state.snapshot(...) end

---@param ... any
---@return any
function sd_state.get_revision(...) end

---@param ... any
---@return any
function sd_state.is_authority(...) end

---@class SdStorageApi
local sd_storage = {}

---@param ... any
---@return any
function sd_storage.get(...) end

---@param ... any
---@return any
function sd_storage.set(...) end

---@param ... any
---@return any
function sd_storage.delete(...) end

---@param ... any
---@return any
function sd_storage.clear(...) end

---@param ... any
---@return any
function sd_storage.snapshot(...) end

---@class SdTimerApi
local sd_timer = {}

---@param ... any
---@return any
function sd_timer.after(...) end

---@param ... any
---@return any
function sd_timer.every(...) end

---@param ... any
---@return any
function sd_timer.sequence(...) end

---@param ... any
---@return any
function sd_timer.cancel(...) end

---@param ... any
---@return any
function sd_timer.clear(...) end

---@class SdBusApi
local sd_bus = {}

---@param ... any
---@return any
function sd_bus.publish(...) end

---@param ... any
---@return any
function sd_bus.subscribe(...) end

---@param ... any
---@return any
function sd_bus.unsubscribe(...) end

---@param ... any
---@return any
function sd_bus.has(...) end

---@param ... any
---@return any
function sd_bus.providers(...) end

---@class SdNetApi
local sd_net = {}

---@param ... any
---@return any
function sd_net.send(...) end

---@param ... any
---@return any
function sd_net.broadcast(...) end

---@param ... any
---@return any
function sd_net.on(...) end

---@param ... any
---@return any
function sd_net.off(...) end

---@param ... any
---@return any
function sd_net.get_limits(...) end

---@class SdTimeApi
local sd_time = {}

---@param ... any
---@return any
function sd_time.get_scale(...) end

---@param ... any
---@return any
function sd_time.get_state(...) end

---@param ... any
---@return any
function sd_time.set_scale(...) end

---@param ... any
---@return any
function sd_time.step(...) end

---@class SdRngApi
local sd_rng = {}

---@param ... any
---@return any
function sd_rng.get_seed(...) end

---@param ... any
---@return any
function sd_rng.set_seed(...) end

---@class SdNavApi
local sd_nav = {}

---@param ... any
---@return any
function sd_nav.get_grid(...) end

---@param ... any
---@return any
function sd_nav.test_segment(...) end

---@class SdSceneApi
local sd_scene = {}

---@param ... any
---@return any
function sd_scene.get_state(...) end

---@param ... any
---@return any
function sd_scene.switch_region(...) end

---@class SdWavesApi
local sd_waves = {}

---@param ... any
---@return any
function sd_waves.get_state(...) end

---@param ... any
---@return any
function sd_waves.get_schedule(...) end

---@class SdSpellsApi
local sd_spells = {}

---@param ... any
---@return any
function sd_spells.register(...) end

---@param ... any
---@return any
function sd_spells.get(...) end

---@param ... any
---@return any
function sd_spells.list(...) end

---@param ... any
---@return any
function sd_spells.select(...) end

---@param ... any
---@return any
function sd_spells.clear_selection(...) end

---@param ... any
---@return any
function sd_spells.get_selection(...) end

---@param ... any
---@return any
function sd_spells.cast(...) end

---@param ... any
---@return any
function sd_spells.get_effects(...) end

---@class SdItemsApi
local sd_items = {}

---@param ... any
---@return any
function sd_items.register(...) end

---@param ... any
---@return any
function sd_items.get(...) end

---@param ... any
---@return any
function sd_items.list(...) end

---@param ... any
---@return any
function sd_items.grant(...) end

---@class SdEnemiesApi
local sd_enemies = {}

---@param ... any
---@return any
function sd_enemies.register(...) end

---@param ... any
---@return any
function sd_enemies.get(...) end

---@param ... any
---@return any
function sd_enemies.list(...) end

---@param ... any
---@return any
function sd_enemies.spawn(...) end

---@class SdAiApi
local sd_ai = {}

---@param ... any
---@return any
function sd_ai.register(...) end

---@param ... any
---@return any
function sd_ai.get_state(...) end

---@param ... any
---@return any
function sd_ai.list(...) end

---@param ... any
---@return any
function sd_ai.set_target(...) end

---@param ... any
---@return any
function sd_ai.set_move_goal(...) end

---@param ... any
---@return any
function sd_ai.stop(...) end

---@param ... any
---@return any
function sd_ai.clear(...) end

---@class SdAudioApi
local sd_audio = {}

---@param ... any
---@return any
function sd_audio.play_sample(...) end

---@param ... any
---@return any
function sd_audio.play_stream(...) end

---@param ... any
---@return any
function sd_audio.stop(...) end

---@param ... any
---@return any
function sd_audio.set_volume(...) end

---@param ... any
---@return any
function sd_audio.get_state(...) end

---@param ... any
---@return any
function sd_audio.clear(...) end

---@param ... any
---@return any
function sd_audio.is_available(...) end

---@class SdCameraApi
local sd_camera = {}

---@param ... any
---@return any
function sd_camera.get_state(...) end

---@param ... any
---@return any
function sd_camera.set_focus(...) end

---@param ... any
---@return any
function sd_camera.clear_focus(...) end

---@param ... any
---@return any
function sd_camera.shake(...) end

---@class SdSpritesApi
local sd_sprites = {}

---@param ... any
---@return any
function sd_sprites.register(...) end

---@param ... any
---@return any
function sd_sprites.unregister(...) end

---@param ... any
---@return any
function sd_sprites.get(...) end

---@param ... any
---@return any
function sd_sprites.list(...) end

---@param ... any
---@return any
function sd_sprites.get_limits(...) end

---@class SdDrawApi
local sd_draw = {}

---@param ... any
---@return any
function sd_draw.text(...) end

---@param ... any
---@return any
function sd_draw.rect(...) end

---@param ... any
---@return any
function sd_draw.line(...) end

---@param ... any
---@return any
function sd_draw.sprite(...) end

---@param ... any
---@return any
function sd_draw.world_to_screen(...) end

---@param ... any
---@return any
function sd_draw.get_viewport(...) end

---@param ... any
---@return any
function sd_draw.get_sprite_info(...) end

---@param ... any
---@return any
function sd_draw.get_limits(...) end

---@class SdBotsApi
local sd_bots = {}

---@param ... any
---@return any
function sd_bots.create(...) end

---@param ... any
---@return any
function sd_bots.destroy(...) end

---@param ... any
---@return any
function sd_bots.clear(...) end

---@param ... any
---@return any
function sd_bots.update(...) end

---@param ... any
---@return any
function sd_bots.move_to(...) end

---@param ... any
---@return any
function sd_bots.stop(...) end

---@param ... any
---@return any
function sd_bots.face(...) end

---@param ... any
---@return any
function sd_bots.face_target(...) end

---@param ... any
---@return any
function sd_bots.cast(...) end

---@param ... any
---@return any
function sd_bots.get_count(...) end

---@param ... any
---@return any
function sd_bots.get_state(...) end

---@param ... any
---@return any
function sd_bots.get_participant_state(...) end

---@param ... any
---@return any
function sd_bots.get_participants(...) end

---@param ... any
---@return any
function sd_bots.get_nameplate(...) end

---@param ... any
---@return any
function sd_bots.get_skill_choices(...) end

---@param ... any
---@return any
function sd_bots.choose_skill(...) end

---@param ... any
---@return any
function sd_bots.debug_sync_level_up(...) end

---@param ... any
---@return any
function sd_bots.resolve_primary_entry(...) end

---@param ... any
---@return any
function sd_bots.get_primary_attack_window(...) end

---@class SdUiApi
local sd_ui = {}

---@param ... any
---@return any
function sd_ui.get_surface_id(...) end

---@param ... any
---@return any
function sd_ui.get_snapshot(...) end

---@param ... any
---@return any
function sd_ui.find_element(...) end

---@param ... any
---@return any
function sd_ui.find_action(...) end

---@param ... any
---@return any
function sd_ui.get_action_dispatch(...) end

---@param ... any
---@return any
function sd_ui.activate_action(...) end

---@param ... any
---@return any
function sd_ui.activate_element(...) end

---@param ... any
---@return any
function sd_ui.get_state(...) end

---@param ... any
---@return any
function sd_ui.perform(...) end

---@param ... any
---@return any
function sd_ui.create_surface(...) end

---@param ... any
---@return any
function sd_ui.create_panel(...) end

---@param ... any
---@return any
function sd_ui.create_label(...) end

---@param ... any
---@return any
function sd_ui.create_button(...) end

---@param ... any
---@return any
function sd_ui.show(...) end

---@param ... any
---@return any
function sd_ui.hide(...) end

---@param ... any
---@return any
function sd_ui.destroy(...) end

---@param ... any
---@return any
function sd_ui.set_text(...) end

---@param ... any
---@return any
function sd_ui.set_enabled(...) end

---@param ... any
---@return any
function sd_ui.focus(...) end

---@param ... any
---@return any
function sd_ui.get_authored_state(...) end

---@class SdInputApi
local sd_input = {}

---@param ... any
---@return any
function sd_input.press_key(...) end

---@param ... any
---@return any
function sd_input.press_binding(...) end

---@param ... any
---@return any
function sd_input.press_scancode(...) end

---@param ... any
---@return any
function sd_input.click_normalized(...) end

---@param ... any
---@return any
function sd_input.hold_mouse_left_frames(...) end

---@param ... any
---@return any
function sd_input.hold_mouse_right_frames(...) end

---@param ... any
---@return any
function sd_input.hold_movement_frames(...) end

---@param ... any
---@return any
function sd_input.set_native_control_allowance_frames(...) end

---@param ... any
---@return any
function sd_input.pin_manual_primary_target(...) end

---@param ... any
---@return any
function sd_input.clear_mouse_left(...) end

---@param ... any
---@return any
function sd_input.clear_mouse_right(...) end

---@param ... any
---@return any
function sd_input.clear_local_cast_state(...) end

---@param ... any
---@return any
function sd_input.get_mouse_left_state(...) end

---@param ... any
---@return any
function sd_input.get_mouse_right_state(...) end

---@param ... any
---@return any
function sd_input.queue_local_spell_cast(...) end

---@param ... any
---@return any
function sd_input.queue_local_enemy_damage_claim(...) end

---@class SdGameplayApi
local sd_gameplay = {}

---@param ... any
---@return any
function sd_gameplay.start_waves(...) end

---@param ... any
---@return any
function sd_gameplay.enable_combat_prelude(...) end

---@param ... any
---@return any
function sd_gameplay.set_manual_enemy_spawner_test_mode(...) end

---@param ... any
---@return any
function sd_gameplay.set_remote_progression_reconcile_suppressed_for_test(...) end

---@param ... any
---@return any
function sd_gameplay.get_manual_enemy_spawner_state(...) end

---@param ... any
---@return any
function sd_gameplay.get_combat_state(...) end

---@param ... any
---@return any
function sd_gameplay.get_selection_debug_state(...) end

---@param ... any
---@return any
function sd_gameplay.spawn_manual_run_enemy(...) end

---@param ... any
---@return any
function sd_gameplay.get_last_manual_run_enemy_spawn(...) end

---@param ... any
---@return any
function sd_gameplay.clear_manual_run_enemy_freeze(...) end

---@param ... any
---@return any
function sd_gameplay.retire_test_run_player_created_actors(...) end

---@param ... any
---@return any
function sd_gameplay.set_run_enemy_health(...) end

---@class SdPlayerApi
local sd_player = {}

---@param ... any
---@return any
function sd_player.get_state(...) end

---@param ... any
---@return any
function sd_player.get_inventory_state(...) end

---@param ... any
---@return any
function sd_player.equip_inventory_item(...) end

---@param ... any
---@return any
function sd_player.get_progression_book_state(...) end

---@class SdWorldApi
local sd_world = {}

---@param ... any
---@return any
function sd_world.get_state(...) end

---@param ... any
---@return any
function sd_world.get_scene(...) end

---@param ... any
---@return any
function sd_world.list_actors(...) end

---@param ... any
---@return any
function sd_world.get_replicated_actors(...) end

---@param ... any
---@return any
function sd_world.get_run_enemy_by_network_id(...) end

---@param ... any
---@return any
function sd_world.get_replicated_loot(...) end

---@param ... any
---@return any
function sd_world.get_replicated_spell_effects(...) end

---@param ... any
---@return any
function sd_world.get_replicated_air_chains(...) end

---@param ... any
---@return any
function sd_world.request_loot_pickup(...) end

---@param ... any
---@return any
function sd_world.rebind_actor(...) end

---@param ... any
---@return any
function sd_world.spawn_reward(...) end

---@param ... any
---@return any
function sd_world.trigger_enemy_death(...) end

---@class SdHubApi
local sd_hub = {}

---@param ... any
---@return any
function sd_hub.start_testrun(...) end

---@param ... any
---@return any
function sd_hub.open_service(...) end

---@param ... any
---@return any
function sd_hub.get_surface_state(...) end

---@class SdDebugApi
local sd_debug = {}

---@param ... any
---@return any
function sd_debug.trace_function(...) end

---@param ... any
---@return any
function sd_debug.untrace_function(...) end

---@param ... any
---@return any
function sd_debug.list_traces(...) end

---@param ... any
---@return any
function sd_debug.get_last_error(...) end

---@param ... any
---@return any
function sd_debug.get_trace_hits(...) end

---@param ... any
---@return any
function sd_debug.clear_trace_hits(...) end

---@param ... any
---@return any
function sd_debug.watch(...) end

---@param ... any
---@return any
function sd_debug.watch_write(...) end

---@param ... any
---@return any
function sd_debug.watch_write_ptr_field(...) end

---@param ... any
---@return any
function sd_debug.get_write_hits(...) end

---@param ... any
---@return any
function sd_debug.clear_write_hits(...) end

---@param ... any
---@return any
function sd_debug.unwatch(...) end

---@param ... any
---@return any
function sd_debug.list_watches(...) end

---@param ... any
---@return any
function sd_debug.watch_ptr_field(...) end

---@param ... any
---@return any
function sd_debug.snapshot(...) end

---@param ... any
---@return any
function sd_debug.snapshot_ptr_field(...) end

---@param ... any
---@return any
function sd_debug.snapshot_nested_ptr_field(...) end

---@param ... any
---@return any
function sd_debug.snapshot_double_nested_ptr_field(...) end

---@param ... any
---@return any
function sd_debug.snapshot_ptr_chain(...) end

---@param ... any
---@return any
function sd_debug.snapshot_object_ptr_chain(...) end

---@param ... any
---@return any
function sd_debug.diff(...) end

---@param ... any
---@return any
function sd_debug.resolve_ptr_chain(...) end

---@param ... any
---@return any
function sd_debug.resolve_object_ptr_chain(...) end

---@param ... any
---@return any
function sd_debug.dump_ptr_chain(...) end

---@param ... any
---@return any
function sd_debug.dump_object_ptr_chain(...) end

---@param ... any
---@return any
function sd_debug.read_bytes(...) end

---@param ... any
---@return any
function sd_debug.read_string(...) end

---@param ... any
---@return any
function sd_debug.search_bytes(...) end

---@param ... any
---@return any
function sd_debug.resolve_game_address(...) end

---@param ... any
---@return any
function sd_debug.layout_offset(...) end

---@param ... any
---@return any
function sd_debug.query_memory(...) end

---@param ... any
---@return any
function sd_debug.dump_struct(...) end

---@param ... any
---@return any
function sd_debug.dump_vtable(...) end

---@param ... any
---@return any
function sd_debug.read_ptr(...) end

---@param ... any
---@return any
function sd_debug.read_ptr_field(...) end

---@param ... any
---@return any
function sd_debug.switch_region(...) end

---@param ... any
---@return any
function sd_debug.set_run_generation_seed(...) end

---@param ... any
---@return any
function sd_debug.read_u8(...) end

---@param ... any
---@return any
function sd_debug.read_i8(...) end

---@param ... any
---@return any
function sd_debug.read_i16(...) end

---@param ... any
---@return any
function sd_debug.read_u16(...) end

---@param ... any
---@return any
function sd_debug.read_u32(...) end

---@param ... any
---@return any
function sd_debug.read_i32(...) end

---@param ... any
---@return any
function sd_debug.read_float(...) end

---@param ... any
---@return any
function sd_debug.write_u8(...) end

---@param ... any
---@return any
function sd_debug.write_i8(...) end

---@param ... any
---@return any
function sd_debug.write_u16(...) end

---@param ... any
---@return any
function sd_debug.write_i16(...) end

---@param ... any
---@return any
function sd_debug.write_u32(...) end

---@param ... any
---@return any
function sd_debug.write_i32(...) end

---@param ... any
---@return any
function sd_debug.write_float(...) end

---@param ... any
---@return any
function sd_debug.write_ptr(...) end

---@param ... any
---@return any
function sd_debug.queue_nested_sack_inventory_fixture(...) end

---@param ... any
---@return any
function sd_debug.call_thiscall_u32(...) end

---@param ... any
---@return any
function sd_debug.call_thiscall_u32_ret_u32(...) end

---@param ... any
---@return any
function sd_debug.call_thiscall_ret_u32(...) end

---@param ... any
---@return any
function sd_debug.queue_native_poison_behavior_probe(...) end

---@param ... any
---@return any
function sd_debug.queue_native_magic_hit_behavior_probe(...) end

---@param ... any
---@return any
function sd_debug.get_native_magic_hit_behavior_probe_result(...) end

---@param ... any
---@return any
function sd_debug.queue_native_enemy_death_probe(...) end

---@param ... any
---@return any
function sd_debug.get_native_enemy_death_probe_result(...) end

---@param ... any
---@return any
function sd_debug.queue_native_experience_gain_probe(...) end

---@param ... any
---@return any
function sd_debug.get_native_experience_gain_probe_result(...) end

---@param ... any
---@return any
function sd_debug.queue_native_staff_effect_probe(...) end

---@param ... any
---@return any
function sd_debug.get_native_staff_effect_probe_result(...) end

---@param ... any
---@return any
function sd_debug.call_thiscall_out_f32x4_u32(...) end

---@param ... any
---@return any
function sd_debug.get_nav_grid(...) end

---@param ... any
---@return any
function sd_debug.test_nav_segment(...) end

---@param ... any
---@return any
function sd_debug.get_gamenpc_motion(...) end

---@param ... any
---@return any
function sd_debug.get_world_movement_geometry(...) end

---@param ... any
---@return any
function sd_debug.call_cdecl_u32_ret_u32(...) end

---@param ... any
---@return any
function sd_debug.call_cdecl_u32_u32(...) end

---@param ... any
---@return any
function sd_debug.copy_bytes(...) end

---@param ... any
---@return any
function sd_debug.read_field_u8(...) end

---@param ... any
---@return any
function sd_debug.read_field_u32(...) end

---@param ... any
---@return any
function sd_debug.read_field_float(...) end

---@param ... any
---@return any
function sd_debug.write_field_u8(...) end

---@param ... any
---@return any
function sd_debug.write_field_u32(...) end

---@param ... any
---@return any
function sd_debug.write_field_float(...) end

---@param ... any
---@return any
function sd_debug.resolve_native_primary_spell_stats(...) end

---@param ... any
---@return any
function sd_debug.resolve_native_secondary_mana_stats(...) end

---@param ... any
---@return any
function sd_debug.capture_backbuffer(...) end

---@param ... any
---@return any
function sd_debug.reset_local_cast_observation(...) end

---@param ... any
---@return any
function sd_debug.get_local_cast_observation(...) end

---@param ... any
---@return any
function sd_debug.get_actor_modifiers(...) end

---@class SdApi
---@field runtime SdRuntimeApi
---@field events SdEventsApi
---@field state SdStateApi
---@field storage SdStorageApi
---@field timer SdTimerApi
---@field bus SdBusApi
---@field net SdNetApi
---@field time SdTimeApi
---@field rng SdRngApi
---@field nav SdNavApi
---@field scene SdSceneApi
---@field waves SdWavesApi
---@field spells SdSpellsApi
---@field items SdItemsApi
---@field enemies SdEnemiesApi
---@field ai SdAiApi
---@field audio SdAudioApi
---@field camera SdCameraApi
---@field sprites SdSpritesApi
---@field hud SdDrawApi
---@field draw SdDrawApi
---@field bots SdBotsApi
---@field ui SdUiApi
---@field input SdInputApi
---@field gameplay SdGameplayApi
---@field player SdPlayerApi
---@field world SdWorldApi
---@field hub SdHubApi
---@field debug SdDebugApi
---@type SdApi
sd = {
    runtime = sd_runtime,
    events = sd_events,
    state = sd_state,
    storage = sd_storage,
    timer = sd_timer,
    bus = sd_bus,
    net = sd_net,
    time = sd_time,
    rng = sd_rng,
    nav = sd_nav,
    scene = sd_scene,
    waves = sd_waves,
    spells = sd_spells,
    items = sd_items,
    enemies = sd_enemies,
    ai = sd_ai,
    audio = sd_audio,
    camera = sd_camera,
    sprites = sd_sprites,
    hud = sd_draw,
    draw = sd_draw,
    bots = sd_bots,
    ui = sd_ui,
    input = sd_input,
    gameplay = sd_gameplay,
    player = sd_player,
    world = sd_world,
    hub = sd_hub,
    debug = sd_debug,
}

return sd
