local inverse_sqrt_two = 1.0 / math.sqrt(2.0)

return {
  model_format = "solomon-dark-bot-policy",
  model_version = 1,
  observation_version = 1,
  trajectory_version = 1,
  architecture = "mlp-tanh-two-head-v1",
  hidden_size = 48,
  observation_names = {
    "self_hp_ratio",
    "self_mana_ratio",
    "self_level_scaled",
    "wave_scaled",
    "self_move_speed_scaled",
    "self_moving",
    "self_cast_active",
    "self_cast_ready",
    "self_poisoned",
    "self_webbed",
    "self_damage_x4",
    "self_status_active",
    "target_present",
    "target_dx",
    "target_dy",
    "target_distance_scaled",
    "target_contact_distance_scaled",
    "target_hp_ratio",
    "target_radius_scaled",
    "target_in_primary_range",
    "primary_min_range_scaled",
    "primary_max_range_scaled",
    "enemy_count_scaled",
    "threat_count_scaled",
    "nearest_enemy_dx",
    "nearest_enemy_dy",
    "nearest_enemy_distance_scaled",
    "nearest_threat_dx",
    "nearest_threat_dy",
    "nearest_threat_distance_scaled",
    "escape_dx",
    "escape_dy",
    "suggested_move_dx",
    "suggested_move_dy",
    "arena_center_dx",
    "arena_center_dy",
    "arena_center_distance_scaled",
    "arena_x_normalized",
    "arena_y_normalized",
    "edge_pressure",
    "inventory_distinct_scaled",
    "inventory_stack_scaled",
    "potion_stack_scaled",
    "equipment_valid",
    "hat_equipped",
    "robe_equipped",
    "weapon_equipped",
    "ring_count_scaled",
    "amulet_equipped",
    "gold_scaled",
    "progression_active_scaled",
    "progression_visible_scaled",
    "secondary_slot_count_scaled",
    "inventory_truncated",
    "progression_truncated",
    "offensive_damage_multiplier_scaled",
    "offensive_mana_multiplier_scaled",
    "cast_speed_multiplier_scaled",
    "secondary_recharge_multiplier_scaled",
    "primary_available",
    "secondary_1_available",
    "secondary_2_available",
    "secondary_3_available",
    "secondary_4_available",
    "secondary_5_available",
    "secondary_6_available",
    "secondary_7_available",
    "secondary_8_available",
    "element_fire",
    "element_water",
    "element_earth",
    "element_air",
    "element_ether",
    "discipline_mind",
    "discipline_body",
    "discipline_arcane",
    "hp_delta",
    "mana_delta",
    "target_hp_delta",
    "enemy_count_delta",
    "previous_move_dx",
    "previous_move_dy",
    "previous_cast_primary",
    "previous_cast_secondary",
    "time_since_damage_scaled",
    "time_since_cast_scaled",
    "time_since_move_scaled",
  },
  movement_actions = {
    { name = "idle", x = 0.0, y = 0.0 },
    { name = "east", x = 1.0, y = 0.0 },
    {
      name = "southeast",
      x = inverse_sqrt_two,
      y = inverse_sqrt_two,
    },
    { name = "south", x = 0.0, y = 1.0 },
    {
      name = "southwest",
      x = -inverse_sqrt_two,
      y = inverse_sqrt_two,
    },
    { name = "west", x = -1.0, y = 0.0 },
    {
      name = "northwest",
      x = -inverse_sqrt_two,
      y = -inverse_sqrt_two,
    },
    { name = "north", x = 0.0, y = -1.0 },
    {
      name = "northeast",
      x = inverse_sqrt_two,
      y = -inverse_sqrt_two,
    },
  },
  cast_actions = {
    { name = "none", skill_slot = -1 },
    { name = "primary", skill_slot = 0 },
    { name = "secondary_1", skill_slot = 1 },
    { name = "secondary_2", skill_slot = 2 },
    { name = "secondary_3", skill_slot = 3 },
    { name = "secondary_4", skill_slot = 4 },
    { name = "secondary_5", skill_slot = 5 },
    { name = "secondary_6", skill_slot = 6 },
    { name = "secondary_7", skill_slot = 7 },
    { name = "secondary_8", skill_slot = 8 },
  },
  trajectory_fields = {
    "trajectory_version",
    "episode_id",
    "participant_id",
    "simulation_tick",
    "observation",
    "movement_mask",
    "cast_mask",
    "movement_action",
    "cast_action",
    "old_log_probability",
    "old_value",
    "reward",
    "done",
  },
}
