# Export all mapped functions from reverse-engineering/maps/functions.csv
# into reverse-engineering/pseudo-source/<subsystem>/ as decompiled C files.
#
# Each file is stamped with metadata from the CSV. A manifest.csv is written
# to the output root summarizing all exports.
#
# Usage:
#   -postScript .../export_mapped_functions.py
#   -postScript .../export_mapped_functions.py --subsystem=timeline
#   -postScript .../export_mapped_functions.py --csv=C:\path\to\functions.csv
#   -postScript .../export_mapped_functions.py --out=C:\path\to\output
# @category: Analysis

import csv
import os
import re

from ghidra.app.decompiler import DecompInterface


REQUIRED_COLUMNS = [
    "entry_va",
    "subsystem",
    "symbol_name",
    "export",
]


def get_repo_root():
    script_dir = os.path.dirname(getSourceFile().getAbsolutePath())
    return os.path.dirname(os.path.dirname(script_dir))


def get_default_csv_path():
    repo_root = get_repo_root()
    return os.path.join(repo_root, "..", "Decompiled Game",
                        "reverse-engineering", "maps", "functions.csv")


def get_default_output_root():
    repo_root = get_repo_root()
    return os.path.join(repo_root, "..", "Decompiled Game",
                        "reverse-engineering", "pseudo-source")


def parse_args():
    csv_path = None
    output_root = None
    subsystem_filter = None

    args = [a.strip() for a in getScriptArgs() if a.strip()]
    for arg in args:
        if arg.startswith("--csv="):
            csv_path = arg.split("=", 1)[1]
        elif arg.startswith("--out="):
            output_root = arg.split("=", 1)[1]
        elif arg.startswith("--subsystem="):
            subsystem_filter = arg.split("=", 1)[1].strip().lower()
        elif csv_path is None:
            csv_path = arg
        elif output_root is None:
            output_root = arg

    if csv_path is None:
        csv_path = get_default_csv_path()
    if output_root is None:
        output_root = get_default_output_root()

    return os.path.abspath(csv_path), os.path.abspath(output_root), subsystem_filter


def load_rows(csv_path, subsystem_filter):
    if not os.path.exists(csv_path):
        print("ERROR: functions.csv was not found: %s" % csv_path)
        raise SystemExit(1)

    handle = open(csv_path, "rb")
    try:
        reader = csv.DictReader(handle)
        if reader.fieldnames is None:
            print("ERROR: functions.csv is missing a header row")
            raise SystemExit(1)

        missing = [name for name in REQUIRED_COLUMNS if name not in reader.fieldnames]
        if missing:
            print("ERROR: functions.csv is missing columns: %s" % ", ".join(missing))
            raise SystemExit(1)

        rows = []
        seen = set()
        for row in reader:
            entry_va = (row.get("entry_va") or "").strip()
            symbol_name = (row.get("symbol_name") or "").strip()
            subsystem = (row.get("subsystem") or "").strip().lower()
            export_flag = (row.get("export") or "").strip().lower()

            if not entry_va or not symbol_name:
                continue
            if entry_va in seen:
                continue
            seen.add(entry_va)
            if export_flag not in ["1", "true", "yes", "y"]:
                continue
            if subsystem_filter and subsystem != subsystem_filter:
                continue

            rows.append(row)
        return rows
    finally:
        handle.close()


def sanitize(text):
    value = re.sub(r"[^A-Za-z0-9._-]+", "_", text.strip())
    return value.strip("._") or "unknown"


def ensure_dir(path):
    if not os.path.isdir(path):
        os.makedirs(path)


def build_header(row, status):
    lines = [
        "/*",
        " * Auto-generated by tools/ghidra-scripts/export_mapped_functions.py",
        " *",
        " * entry_va:           %s" % (row.get("entry_va") or "").strip(),
        " * subsystem:          %s" % (row.get("subsystem") or "").strip(),
        " * symbol_name:        %s" % (row.get("symbol_name") or "").strip(),
        " * kind:               %s" % (row.get("kind") or "").strip(),
        " * calling_convention: %s" % (row.get("calling_convention") or "").strip(),
        " * signature_note:     %s" % (row.get("signature_note") or "").strip(),
        " * status:             %s" % (row.get("status") or "").strip(),
        " * export_status:      %s" % status,
        " * notes:              %s" % (row.get("notes") or "").strip(),
        " */",
        "",
    ]
    return "\n".join(lines)


def main():
    csv_path, output_root, subsystem_filter = parse_args()
    rows = load_rows(csv_path, subsystem_filter)
    ensure_dir(output_root)

    print("=== EXPORT MAP ===")
    print("CSV_PATH %s" % csv_path)
    print("OUTPUT_ROOT %s" % output_root)
    print("ROW_COUNT %d" % len(rows))
    print("SUBSYSTEM_FILTER %s" % (subsystem_filter or "<all>"))
    print()

    decomp = DecompInterface()
    decomp.openProgram(currentProgram)

    exported = 0
    errors = 0
    manifest_rows = []

    try:
        for row in rows:
            if monitor.isCancelled():
                print("ERROR: cancelled")
                break

            entry_va = row["entry_va"].strip()
            symbol_name = row["symbol_name"].strip()
            subsystem = sanitize((row.get("subsystem") or "misc").lower())
            va_clean = entry_va.upper().replace("0X", "")

            out_dir = os.path.join(output_root, subsystem)
            ensure_dir(out_dir)
            out_path = os.path.join(out_dir, "%s__%s.c" % (va_clean, sanitize(symbol_name)))

            addr = toAddr(entry_va)
            func = getFunctionAt(addr)

            if func is None:
                status = "missing_function"
                body = "/* ERROR: no function at %s */\n" % entry_va
                errors += 1
            else:
                result = decomp.decompileFunction(func, 600, monitor)
                decompiled = None
                if result is not None:
                    decompiled = result.getDecompiledFunction()

                if result is None or not result.decompileCompleted() or decompiled is None:
                    # Fallback: emit instruction dump instead of empty stub
                    status = "instruction_dump_fallback"
                    lines = [
                        "/* ERROR: decompilation failed for %s (%s) */" % (symbol_name, entry_va),
                        "/* Falling back to raw instruction dump. */",
                        "",
                        "/*",
                    ]
                    listing = currentProgram.getListing()
                    insts = listing.getInstructions(func.getBody(), True)
                    while insts.hasNext():
                        inst = insts.next()
                        lines.append(" * %s %s" % (inst.getAddress(), inst))
                    lines.extend([" */", ""])
                    body = "\n".join(lines)
                    errors += 1
                else:
                    status = "ok"
                    body = str(decompiled.getC())

            text = build_header(row, status) + body
            if not text.endswith("\n"):
                text += "\n"

            handle = open(out_path, "wb")
            try:
                handle.write(text.encode("utf-8"))
            finally:
                handle.close()

            print("EXPORT %s -> %s [%s]" % (entry_va, out_path, status))
            manifest_rows.append([entry_va, subsystem, symbol_name, out_path, status])
            exported += 1

    finally:
        decomp.dispose()

    # Write manifest
    manifest_path = os.path.join(output_root, "manifest.csv")
    handle = open(manifest_path, "wb")
    try:
        writer = csv.writer(handle)
        writer.writerow(["entry_va", "subsystem", "symbol_name", "export_path", "export_status"])
        for mrow in manifest_rows:
            writer.writerow(mrow)
    finally:
        handle.close()

    print()
    print("=== SUMMARY ===")
    print("EXPORTED %d" % exported)
    print("ERRORS %d" % errors)
    print("MANIFEST %s" % manifest_path)


main()
