#!/usr/bin/env python3
"""Generate the Lua policy skill table from the pinned native catalog."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "docs/reverse-engineering/native-skill-catalog.json"
OUTPUT = ROOT / "mods/bot-brain/scripts/policy_skill_catalog.lua"

SECONDARY_IDS = {
    11,
    12,
    15,
    21,
    23,
    27,
    30,
    35,
    41,
    45,
    46,
    48,
    49,
    50,
    51,
    54,
    72,
    73,
    74,
    76,
    77,
    78,
    79,
}
PRIMARY_IDS = {8, 16, 24, 32, 40}
ROOT_IDS = set(range(8))


def values(config: dict[str, object], key: str) -> list[float] | None:
    value = config.get(key)
    if value is None:
        return None
    if not isinstance(value, list):
        value = [value]
    return [float(item) for item in value]


def value_at(rows: list[float] | None, rank: int) -> float:
    if not rows:
        return 0.0
    return rows[min(max(rank, 0), len(rows) - 1)]


def lua_number(value: float) -> str:
    if value == int(value):
        return f"{int(value)}.0"
    return repr(value)


def lua_array(rows: list[float]) -> str:
    return "{" + ", ".join(lua_number(value) for value in rows) + "}"


def main() -> None:
    source = json.loads(SOURCE.read_text(encoding="utf-8"))
    output = [
        "-- Generated by tools/generate_ml_bot_skill_catalog_lua.py from",
        "-- docs/reverse-engineering/native-skill-catalog.json.",
        "return {",
    ]
    for skill in source["skills"]:
        skill_id = int(skill["id"])
        config = skill.get("config") or {}
        max_rank = int(config.get("mMaxLevel", 0))
        cap_rank = int(config.get("mCapLevel", max_rank))
        rank_count = max(max_rank, 0) + 1
        mana = values(config, "mManaCost")
        damage = values(config, "mDamage")
        damage1 = values(config, "mDamage1")
        damage2 = values(config, "mDamage2")
        cooldown = values(config, "mCooldown")
        radius = values(config, "mRadius")
        duration = values(config, "mDuration")
        value = values(config, "mValue")
        concentration = values(config, "mConcentration")
        chance = values(config, "mChance")
        quantity = values(config, "mQuantity")
        strength = values(config, "mStrength")

        damage_min: list[float] = []
        damage_max: list[float] = []
        quantity_or_strength: list[float] = []
        for rank in range(rank_count):
            damage_values = [
                value_at(row, rank)
                for row in (damage, damage1, damage2)
                if row is not None
            ]
            damage_min.append(min(damage_values, default=0.0))
            damage_max.append(max(damage_values, default=0.0))
            quantity_or_strength.append(
                max(
                    value_at(quantity, rank),
                    value_at(strength, rank),
                )
            )

        is_primary = skill_id in PRIMARY_IDS
        is_secondary = skill_id in SECONDARY_IDS
        is_weld = skill_id == 52
        is_passive = (
            skill_id not in ROOT_IDS
            and not is_primary
            and not is_secondary
            and not is_weld
        )
        is_utility = skill_id in ROOT_IDS or is_passive or is_weld
        family = str(skill.get("family") or "runtime_only")
        fields = [
            f'family = "{family}"',
            f"cap_rank = {cap_rank}",
            f"max_rank = {max_rank}",
            f"is_primary = {str(is_primary).lower()}",
            f"is_secondary = {str(is_secondary).lower()}",
            f"is_passive = {str(is_passive).lower()}",
            f"is_utility = {str(is_utility).lower()}",
            f"is_weld = {str(is_weld).lower()}",
            f"mana_cost_present = {str(mana is not None).lower()}",
            f"damage_min_present = {str(bool(damage or damage1 or damage2)).lower()}",
            f"damage_max_present = {str(bool(damage or damage1 or damage2)).lower()}",
            "range_present = false",
            f"cooldown_present = {str(cooldown is not None).lower()}",
            f"radius_present = {str(radius is not None).lower()}",
            f"duration_present = {str(duration is not None).lower()}",
            f"value_present = {str(value is not None).lower()}",
            f"concentration_present = {str(concentration is not None).lower()}",
            f"chance_present = {str(chance is not None).lower()}",
            f"quantity_or_strength_present = {str(quantity is not None or strength is not None).lower()}",
            f"mana_cost = {lua_array([value_at(mana, rank) for rank in range(rank_count)])}",
            f"damage_min = {lua_array(damage_min)}",
            f"damage_max = {lua_array(damage_max)}",
            f"range = {lua_array([0.0] * rank_count)}",
            f"cooldown = {lua_array([value_at(cooldown, rank) for rank in range(rank_count)])}",
            f"radius = {lua_array([value_at(radius, rank) for rank in range(rank_count)])}",
            f"duration = {lua_array([value_at(duration, rank) for rank in range(rank_count)])}",
            f"value = {lua_array([value_at(value, rank) for rank in range(rank_count)])}",
            f"concentration = {lua_array([value_at(concentration, rank) for rank in range(rank_count)])}",
            f"chance = {lua_array([value_at(chance, rank) for rank in range(rank_count)])}",
            f"quantity_or_strength = {lua_array(quantity_or_strength)}",
        ]
        output.append(f"  [{skill_id}] = {{")
        for field in fields:
            output.append(f"    {field},")
        output.append("  },")
    output.append("}")
    OUTPUT.write_text("\n".join(output) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
