#!/usr/bin/env python3
"""Generate native scene-capture atlas spans from the reviewed asset map."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


SPRITE_STRIDE = 0xC4


def _integer(value: int | str) -> int:
    return int(value, 0) if isinstance(value, str) else value


def _coalesced_destinations(atlas: dict) -> list[dict]:
    result: list[dict] = []
    for destination in atlas["destinations"]:
        if destination["destination_kind"] == "aux":
            continue
        current = {
            "kind": destination["destination_kind"],
            "field": _integer(destination["object_field"]),
            "first": destination["first_record"],
            "count": destination["record_count"],
        }
        if current["kind"] not in {"inline", "array"}:
            raise ValueError(
                f"unsupported destination kind {current['kind']!r} in {atlas['name']}"
            )
        if result and current["kind"] == "inline":
            previous = result[-1]
            expected_field = previous["field"] + previous["count"] * SPRITE_STRIDE
            expected_record = previous["first"] + previous["count"]
            if (
                previous["kind"] == "inline"
                and current["field"] == expected_field
                and current["first"] == expected_record
            ):
                previous["count"] += current["count"]
                continue
        result.append(current)
    return result


def render(source: Path) -> str:
    document = json.loads(source.read_text(encoding="utf-8"))
    if document.get("schema") != "solomon-dark-native-asset-object-map-v1":
        raise ValueError("native asset object map schema drifted")
    atlases = document["atlases"]
    if len(atlases) != 28:
        raise ValueError(f"expected 28 native atlases, found {len(atlases)}")

    lines = [
        "// Generated by tools/generate_native_scene_atlas_spans.py.",
        "// Source: docs/reverse-engineering/native-asset-object-map.json",
        "constexpr NativeSceneAtlasSpan kNativeSceneAtlasSpans[] = {",
    ]
    for atlas in atlases:
        singleton = _integer(atlas["singleton"])
        for destination in _coalesced_destinations(atlas):
            kind = "Inline" if destination["kind"] == "inline" else "Array"
            lines.append(
                "    {\"%s\", 0x%08X, NativeSceneAtlasSpanKind::%s, "
                "0x%04X, %d, %d},"
                % (
                    atlas["name"],
                    singleton,
                    kind,
                    destination["field"],
                    destination["first"],
                    destination["count"],
                )
            )
    lines.extend(["};", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--source",
        type=Path,
        default=Path("docs/reverse-engineering/native-asset-object-map.json"),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(
            "SolomonDarkModLoader/src/native_scene_capture/generated_atlas_spans.inl"
        ),
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render(args.source)
    if args.check:
        if not args.output.is_file() or args.output.read_text(encoding="utf-8") != rendered:
            raise SystemExit("native scene atlas spans are stale")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
