#!/usr/bin/env python3
"""Owner-approved inventory of legacy verifiers requiring process isolation."""

from __future__ import annotations


AUDITED_LEGACY_VERIFIERS = (
    "tools/verify_enemy_damage_claim_sync.py",
    "tools/verify_flat_multiplayer_boneyard.py",
    "tools/verify_hub_student_seed_viability.py",
    "tools/verify_local_multiplayer_sync.py",
    "tools/verify_multiplayer_all_stat_sync.py",
    "tools/verify_multiplayer_all_upgrade_sync.py",
    "tools/verify_multiplayer_animation_mana_elements.py",
    "tools/verify_multiplayer_battle_siege_behavior_sync.py",
    "tools/verify_multiplayer_concentration_behavior_context.py",
    "tools/verify_multiplayer_defense_behavior_sync.py",
    "tools/verify_multiplayer_enemy_soft_reconciliation.py",
    "tools/verify_multiplayer_faster_caster_behavior_sync.py",
    "tools/verify_multiplayer_fireball_embers_effect_sync.py",
    "tools/verify_multiplayer_fireball_explode_effect_sync.py",
    "tools/verify_multiplayer_firewalker_effect_sync.py",
    "tools/verify_multiplayer_focus_behavior_sync.py",
    "tools/verify_multiplayer_gold_pickup_authority.py",
    "tools/verify_multiplayer_host_owned_level_up_sync.py",
    "tools/verify_multiplayer_hub_inventory_shop_sync.py",
    "tools/verify_multiplayer_hub_shop_ownership.py",
    "tools/verify_multiplayer_inventory_audit.py",
    "tools/verify_multiplayer_late_join_owned_state.py",
    "tools/verify_multiplayer_late_join_upgrade_catchup.py",
    "tools/verify_multiplayer_level_up_barrier_sync.py",
    "tools/verify_multiplayer_level_up_offer_sync.py",
    "tools/verify_multiplayer_lightning_chaining_effect_sync.py",
    "tools/verify_multiplayer_loot_drop_materialization.py",
    "tools/verify_multiplayer_meditation_behavior_sync.py",
    "tools/verify_multiplayer_mindstar_behavior_sync.py",
    "tools/verify_multiplayer_native_item_inventory_sync.py",
    "tools/verify_multiplayer_native_potion_inventory_sync.py",
    "tools/verify_multiplayer_orb_pickup_authority.py",
    "tools/verify_multiplayer_persistent_status_sync.py",
    "tools/verify_multiplayer_player_visibility.py",
    "tools/verify_multiplayer_powerup_sync.py",
    "tools/verify_multiplayer_primary_kill_stress.py",
    "tools/verify_multiplayer_progression_catalog.py",
    "tools/verify_multiplayer_progression_ledger_sync.py",
    "tools/verify_multiplayer_regenerate_behavior_sync.py",
    "tools/verify_multiplayer_ring_of_fire_multikill_stability.py",
    "tools/verify_multiplayer_rush_behavior_sync.py",
    "tools/verify_multiplayer_skill_picker_visual_identity.py",
    "tools/verify_multiplayer_staff_stat_behavior_sync.py",
    "tools/verify_multiplayer_targeted_spell_matrix.py",
    "tools/verify_multiplayer_telekinesis_behavior_sync.py",
    "tools/verify_multiplayer_third_observer_upgrade_sync.py",
    "tools/verify_multiplayer_transient_status_sync.py",
    "tools/verify_multiplayer_webbed_status_sync.py",
    "tools/verify_native_enemy_death_and_loot_sync.py",
    "tools/verify_player_damage_visual_sync.py",
    "tools/verify_player_health_death_sync.py",
    "tools/verify_real_input_spell_cast_sync.py",
    "tools/verify_run_enemy_materialization_catchup.py",
    "tools/verify_run_enemy_seed_viability.py",
    "tools/verify_run_enemy_target_authority.py",
    "tools/verify_run_world_snapshot.py",
    "tools/verify_spell_cast_sync.py",
    "tools/verify_world_snapshot_reconciliation.py",
)
