#include "bot_actor_calls/player_runtime_and_progression_calls.inl"
#include "bot_actor_calls/local_player_cast_shim.inl"
#include "bot_actor_calls/game_npc_calls.inl"
#include "bot_actor_calls/actor_world_and_visual_calls.inl"
#include "bot_actor_calls/spell_cast_calls.inl"
#include "bot_actor_calls/lifecycle_and_stat_calls.inl"
